### ISSUE TITLE
Return league subscription information

### ISSUE THREAD

**Issue by SSchulze1989** [SSchulze1989/iRLeagueApiCore#124]
# Description
Return the information about the current league subscription if the requesting user has either the admin or organizer role:
- Subscription type (Expired, Trial, Paid, Lifetime)
- Expiration Date

# Tasks
- [x] Add Required fields to LeagueModel dto
- [x] Add handling for data
  - [x] Only return these values if user is in Admin or Organizer role
