### ISSUE TITLE
Feature: Add Admin panel functions to manage payments

### ISSUE THREAD

**Issue by SSchulze1989** [SSchulze1989/iRLeagueApiCore#135]
# Description
Managing of payments and subscriptions will first start off manually and then be enhanced by an automated process later.
In order to manage subscriptions manually the API should be enhanced by admin methods to manage the subscriptions status of leagues.

# Tasks
- [x] Add Endpoint to view all Subscriptions
- [x] Add Endpoint to filter Subscriptions by league
- [x] Add Endpoint to get single Payment
- [x] Add Endpoint to activate a subscription for a league
  - [x] This should automatically set the League subscription state and expired date as well
- [x] Add Endpoint to deactivate a subscription
  - [x] This should automatically set the League subscription state and expired date as well
- [x] Add Endpoint to set the subscription state of a league without payment

# Additional Info
- [x] All endpoints should be available in the api documentation but not part of the API client
