### ISSUE TITLE
Feature: Automatic penalties

### ISSUE THREAD

**Issue by SSchulze1989** [SSchulze1989/iRLeagueApiCore#140]
# Description
Add option to configure automatic penalties that are applied when one or more conditions are fulfilled

Possible conditions
- [x] **Incidents** add penalty points per incident count

# Tasks
- [x] Create data transfer model for automatic penalty configuration
- [x] Create Entity for automatic penalty configuration
- [x] Implement handling of configuration through API
- [x] Calculate `AddPenalties` from automatic configuration during result calculation
