### ISSUE TITLE
Feature: Allow upload of iRacing Team results

### ISSUE THREAD

**Issue by SSchulze1989** [SSchulze1989/iRLeagueApiCore#150]
## Description
Currently the API will throw an Error when trying to upload a result from a team event.
This is because the backend is expecting a driver result row in the top level of the json session results but instead finds a team. The individual driver rows can be found one level deeper.

## What needs to be changed?
To enable the upload of team results the backend would need to check if it is a team result and then catch the individual driver rows one level below. Right now there it seems not required to save any data from the team result row directly because all of the information can be later taken from the individual driver rows.
Additionally the Teams need to be assigned from the `teamId` or `name`.
If a team does not yet exist it should be newly created.
If a team does exists its driver list should be updated according to the drivers in the result:
- Add drivers to the team if not already in there
- Do not remove drivers from the team if they are not in the result.
- Remove driver from team / assign to different team if driver is part of a different team in the result

## Tasks

- [x] Add check to detect a team result
- [x] Get driver result rows from `driver_results` field
- [x] Add unit tests using a test team result set
- [x] Add `IRacingTeamId` field to `TeamEntity` to identify which team from iracing is already created
- [x] Check for existing teams and create new / update existing according to drivers in the current result
