### ISSUE TITLE
Feature: Add the number of races scored to standings

### ISSUE THREAD

**Issue by SSchulze1989** [SSchulze1989/iRLeagueApiCore#158]
## Description
In order to determine which races a driver did score or not score based on the Point System Filters this information should be added to the standings rows.

## Tasks
- [x] Add columns in database schema
- [x] Add mapping for columns
- [x] Calculate values during standing calculations
